### ISSUE TITLE
Needs more cowbell

### ISSUE THREAD

**Issue by joshistoast** [utsavsheth/DesignSystemTest#2]
nuff said

**Comment by utsavsheth** [comment]
Testing... I want to connect Figma with GitHub. 1st step is done... Now I don't know about the JSON... Help me if you can...

Have you heard about Token Studio?

**Comment by joshistoast** [comment]
> Testing... I want to connect Figma with GitHub. 1st step is done... Now I don't know about the JSON... Help me if you can...
> 
> Have you heard about Token Studio?

Haven't heard of it, honestly I'm not even sure how a figma connection to github would contribute to a workflow or work in general

**Comment by utsavsheth** [comment]
Here is the flow

We need to use Figma token studio, Define all colours and styling stuff as a token in studio and connect with github... Tool generated JSON file.

**Comment by joshistoast** [comment]
> Here is the flow
> 
> We need to use Figma token studio, Define all colours and styling stuff as a token in studio and connect with github... Tool generated JSON file.

Read through [these docs](https://docs.tokens.studio/sync/github)?

**Comment by utsavsheth** [comment]
Thanks
